name: Swift

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode 16
      run: sudo xcode-select -s "/Applications/Xcode_16.2.app/Contents/Developer"
    
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
      
    - name: Build Release Binary
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        swift build -c release
        cd .build/release
        zip -r ImageDupes-macOS.zip ImageDupes
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: .build/release/ImageDupes-macOS.zip
        generate_release_notes: true